import Head from 'next/head'
import { fetcher } from '../util'
import { useSWRInfinite } from 'swr'
import InfiniteScroll from 'react-infinite-scroll-component'

export async function getStaticProps() {
  // `getStaticProps` is invoked on the server-side,
  // so this `fetcher` function will be executed on the server-side.
  const posts = await fetcher('/posts', 1, 20)
  return { props: { posts } }
}

// A function to get the SWR key of each page,
// its return value will be accepted by `fetcher`.
// If `null` is returned, the request of that page won't start.
const getKey = (pageIndex, previousPageData) => {
  if (previousPageData && !previousPageData.length) return null // reached the end
  return ['/posts', pageIndex + 1, 10]
}

export default function Home({ posts }) {
  const { data, size, setSize } = useSWRInfinite(getKey, fetcher, {
    initialSize: 2,
    initialData: [posts],
  })
  if (!data) return 'loading'

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfiniteScroll
        dataLength={data.flat().length}
        next={() => setSize(size + 1)}
        hasMore={data[data.length - 1].length > 0}
        loader={<h4>Loading...</h4>}
      >
        {data.map(function mapPostsEveryPagination(posts) {
          return posts.map(function mapPostsToElement(post) {
            return (
              <div key={post.id}>
                <p>{post.id}</p>
                <p>{post.title}</p>
              </div>
            )
          })
        })}
      </InfiniteScroll>
    </div>
  )
}
